# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Deployment

on:
  repository_dispatch:
    types: certnidmobilesdk_release

jobs:
  download_artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private repository
        uses: actions/checkout@v3
        with:
          repository: certn-id-mobile-sdk/ios-sdk-private
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false

      - name: Create version directory
        run: mkdir -p CertnIDMobileSDK/${{ github.event.client_payload.version }}

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: CertnIDMobileSDK
          path: CertnIDMobileSDK/${{ github.event.client_payload.version }}

      - name: Unzip artifacts
        run: unzip -o CertnIDMobileSDK/${{ github.event.client_payload.version }}/CertnIDMobileSDK.zip -d CertnIDMobileSDK/${{ github.event.client_payload.version }}

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Add artifacts for version ${{ github.event.client_payload.version }}"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main